---
dependencies: []

galaxy_info:
  author: Sam Culley
  description: Dotfile installation for UNIX/Linux.
  license: "license (MIT)"
  min_ansible_version: "2.1"
  platforms:
    - name: GenericUNIX
      versions:
        - all
    - name: GenericBSD
      versions:
        - all
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - development
    - system
    - dotfiles
    - configuration
