---
- name: Ensure powerlevel10k is installed
  community.general.homebrew:
    name: powerlevel10k
    state: present

- name: Insert p10k block in .zshrc
  blockinfile:
    path: "~/.zshrc"
    insertafter: EOF
    block: |
      # powerlevel10k
      [[ ! -f /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme ]] || source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme
      [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
  when: powerlevel10k_zshrc_block

- name: Download .p10k.zsh
  get_url:
    url: "{{ powerlevel10k_config_file_url }}"
    dest: "~/.p10k.zsh"
    mode: '0700'
