---
- name: Ensure powerlevel10k is installed
  community.general.homebrew:
    name: powerlevel10k
    state: present

- name: Insert p10k block in .zshrc
  blockinfile:
    path: "~/.zshrc"
    insertafter: "# powerlevel10k"
    block: |
      source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme
      # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
      [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

- name: Download .p10k.zsh
  get_url:
    url: "{{ powerlevel10k_config_file_url }}"
    dest: "~/.p10k.zsh"
    mode: '0700'
